version: "5"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "exampledb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "357789"
    ports:
      - 5432:5432
    volumes:
      - "/var/lib/postgresql/data:/var/lib/postgresql/data:z"

  backend:
    build: backend/DockerDBExample
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/exampledb
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "357789"
    ports:
      - 8080:8080
    depends_on:
      - db
