version: "4.0"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "exampledb"
      POSTGRES_USER: "********"
      POSTGRES_PASSWORD: "********"
    ports:
      - "5432:5432"
    volumes:
      - "/var/lib/postgresql/data:/var/lib/postgresql/data:z"

  backend:
    build:
      context: ./Backend/DockerDBExample
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/exampledb
      SPRING_DATASOURCE_USERNAME: "********"
      SPRING_DATASOURCE_PASSWORD: "********"
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend/frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8080
